### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by amitrathiesh** [Capevace/homebridge-http-tv#3]
Here is my config:

> {
>             "devices": [
>                 {
>                     "name": "Sharp TV",
>                     "serialNumber": "6C000357",
>                     "method": "POST",
>                     "power": {
>                         "onUrl": {
>                             "url": "http://192.168.150.2/Power.cgi/",
>                             "method": "POST",
>                             "body": "power=0&standby=0&ret=&rPOWR=1"
>                         },
>                         "offUrl": {
>                             "url": "http://192.168.150.2/Power.cgi/",
>                             "method": "POST",
>                             "body": "power=1&standby=0&ret=&rPOWR=0"
>                         }
>                     },
>                     "sources": [
>                         {
>                             "name": "HDMI 1",
>                             "url": "http://192.168.150.2/Input.cgi",
>                             "type": 3
>                         }
>                     ],
>                     "model": "PN-R703",
>                     "manufacturer": "Sharp"
>                 }
>             ],
>             "platform": "http-tv"
>  }
> 

The TV shows up on my Home App, but every time I try to use it, I get the following error. What exactly am I missing? The same POST request does work when I use it on HTTP-SWITCH

_Cannot update TV power via HTTP TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/usr/lib/node_modules/homebridge-http-tv/node_modules/node-fetch/lib/index.js:1305:9)
    at /usr/lib/node_modules/homebridge-http-tv/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at Function.fetch [as default] (/usr/lib/node_modules/homebridge-http-tv/node_modules/node-fetch/lib/index.js:1407:9)
    at HTTPTVAccessory.httpRequest (/usr/lib/node_modules/homebridge-http-tv/src/platformAccessory.ts:229:31)
    at HTTPTVAccessory.setActive (/usr/lib/node_modules/homebridge-http-tv/src/platformAccessory.ts:140:15)
    at Active.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at Active.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)_

**Comment by Capevace** [comment]
`onUrl` and `offUrl` only take strings not objects...

That's a usecase I didn't think of, since you can only customise the request body, headers etc for both on and off requests at the same time.

You could fix your issue by specifying the on/off state in URL parameters instead of the POST body. 

I'll have to think about how to improve this without braking other configs.

**Comment by amitrathiesh** [comment]
> `onUrl` and `offUrl` only take strings not objects...
> 
> That's a usecase I didn't think of, since you can only customise the request body, headers etc for both on and off requests at the same time.
> 
> You could fix your issue by specifying the on/off state in URL parameters instead of the POST body.
> 
> I'll have to think about how to improve this without braking other configs.

I was able to get around the issue by creating few php files, first one to turn the tv on, second one to turn it off and similarly for each input. The plugin works great. <3

But in the HOME app, TV shows the icon of HOME, instead of TV. I did see that few other TV plugins had this issue and they fixed it by declaring all tvs as external accessory.

**Comment by ddong3000** [comment]
> > `onUrl` and `offUrl` only take strings not objects...
> > That's a usecase I didn't think of, since you can only customise the request body, headers etc for both on and off requests at the same time.
> > You could fix your issue by specifying the on/off state in URL parameters instead of the POST body.
> > I'll have to think about how to improve this without braking other configs.
> 
> I was able to get around the issue by creating few php files, first one to turn the tv on, second one to turn it off and similarly for each input. The plugin works great. <3
> 
> But in the HOME app, TV shows the icon of HOME, instead of TV. I did see that few other TV plugins had this issue and they fixed it by declaring all tvs as external accessory.

what mean external accessory? 
how can i fix that TV shows the icon of HOME, instead of TV
plz help me

**Comment by ddong3000** [comment]
How can i fix that TV shows the icon of HOME, instead of TV?
Please tell me how fix declaring all tv as external accessory.
Where can I add the publishExternalAccessories code?
plz show your code 🙇🏼‍♂️
